<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;

class AtletaSeeder extends Seeder
{
    public function run(): void
    {
        $atletas = [
            [
                'nomeCompletoUsuario' => 'Lucas Ferreira da Silva',
                'nomeUsuario' => 'lucasf',
                'emailUsuario' => 'lucasf@gmail.com',
                'senhaUsuario' => Hash::make('123456'),
                'nacionalidadeUsuario' => 'Brasileiro',
                'dataNascimentoUsuario' => '2002-05-14',
                'fotoPerfilUsuario' => null,
                'fotoBannerUsuario' => null,
                'bioUsuario' => 'Amante do futebol e da corrida.',
                'alturaCm' => 178.5,
                'pesoKg' => 72.3,
                'peDominante' => 'direito',
                'maoDominante' => 'direita',
                'generoUsuario' => 'Masculino',
                'esporte' => 'Futebol',
                'posicao' => 'Atacante',
                'estadoUsuario' => 'São Paulo',
                'cidadeUsuario' => 'Campinas',
                'categoria' => 'Amador',
                'temporadasUsuario' => '3'
            ],
            [
                'nomeCompletoUsuario' => 'Mariana Costa Oliveira',
                'nomeUsuario' => 'maricosta',
                'emailUsuario' => 'maricosta@gmail.com',
                'senhaUsuario' => Hash::make('123456'),
                'nacionalidadeUsuario' => 'Brasileira',
                'dataNascimentoUsuario' => '2004-11-09',
                'fotoPerfilUsuario' => null,
                'fotoBannerUsuario' => null,
                'bioUsuario' => 'Apaixonada por vôlei e esportes coletivos.',
                'alturaCm' => 182.0,
                'pesoKg' => 68.0,
                'peDominante' => 'direito',
                'maoDominante' => 'direita',
                'generoUsuario' => 'Feminino',
                'esporte' => 'Vôlei',
                'posicao' => 'Levantadora',
                'estadoUsuario' => 'Minas Gerais',
                'cidadeUsuario' => 'Belo Horizonte',
                'categoria' => 'Profissional',
                'temporadasUsuario' => '5'
            ],
            [
                'nomeCompletoUsuario' => 'Rafael Andrade Lima',
                'nomeUsuario' => 'rafael_a',
                'emailUsuario' => 'rafael.a@gmail.com',
                'senhaUsuario' => Hash::make('123456'),
                'nacionalidadeUsuario' => 'Brasileiro',
                'dataNascimentoUsuario' => '1999-02-25',
                'fotoPerfilUsuario' => null,
                'fotoBannerUsuario' => null,
                'bioUsuario' => 'Corredor e triatleta nas horas vagas.',
                'alturaCm' => 174.0,
                'pesoKg' => 69.5,
                'peDominante' => 'direito',
                'maoDominante' => 'direita',
                'generoUsuario' => 'Masculino',
                'esporte' => 'Triatlo',
                'posicao' => 'Competidor',
                'estadoUsuario' => 'Rio de Janeiro',
                'cidadeUsuario' => 'Niterói',
                'categoria' => 'Semi-profissional',
                'temporadasUsuario' => '4'
            ],
            [
                'nomeCompletoUsuario' => 'Beatriz Santos Nogueira',
                'nomeUsuario' => 'bia_nog',
                'emailUsuario' => 'bia.nog@gmail.com',
                'senhaUsuario' => Hash::make('123456'),
                'nacionalidadeUsuario' => 'Brasileira',
                'dataNascimentoUsuario' => '2005-08-12',
                'fotoPerfilUsuario' => null,
                'fotoBannerUsuario' => null,
                'bioUsuario' => 'Atleta de natação desde os 10 anos.',
                'alturaCm' => 170.0,
                'pesoKg' => 60.0,
                'peDominante' => 'direito',
                'maoDominante' => 'direita',
                'generoUsuario' => 'Feminino',
                'esporte' => 'Natação',
                'posicao' => 'Nadadora',
                'estadoUsuario' => 'Paraná',
                'cidadeUsuario' => 'Curitiba',
                'categoria' => 'Juvenil',
                'temporadasUsuario' => '2'
            ],
            [
                'nomeCompletoUsuario' => 'João Victor Mendes',
                'nomeUsuario' => 'joaovm',
                'emailUsuario' => 'joaovm@gmail.com',
                'senhaUsuario' => Hash::make('123456'),
                'nacionalidadeUsuario' => 'Brasileiro',
                'dataNascimentoUsuario' => '2001-03-17',
                'fotoPerfilUsuario' => null,
                'fotoBannerUsuario' => null,
                'bioUsuario' => 'Goleiro com experiência em campeonatos regionais.',
                'alturaCm' => 185.0,
                'pesoKg' => 80.0,
                'peDominante' => 'direito',
                'maoDominante' => 'direita',
                'generoUsuario' => 'Masculino',
                'esporte' => 'Futebol',
                'posicao' => 'Goleiro',
                'estadoUsuario' => 'Bahia',
                'cidadeUsuario' => 'Salvador',
                'categoria' => 'Amador',
                'temporadasUsuario' => '6'
            ],
            [
                'nomeCompletoUsuario' => 'Carla Lima Souza',
                'nomeUsuario' => 'carlinha',
                'emailUsuario' => 'carlinha@gmail.com',
                'senhaUsuario' => Hash::make('123456'),
                'nacionalidadeUsuario' => 'Brasileira',
                'dataNascimentoUsuario' => '2003-07-30',
                'fotoPerfilUsuario' => null,
                'fotoBannerUsuario' => null,
                'bioUsuario' => 'Jogadora de basquete universitário.',
                'alturaCm' => 177.0,
                'pesoKg' => 65.0,
                'peDominante' => 'direito',
                'maoDominante' => 'direita',
                'generoUsuario' => 'Feminino',
                'esporte' => 'Basquete',
                'posicao' => 'Ala',
                'estadoUsuario' => 'São Paulo',
                'cidadeUsuario' => 'Santos',
                'categoria' => 'Universitário',
                'temporadasUsuario' => '3'
            ],
            [
                'nomeCompletoUsuario' => 'Eduardo Rocha Lima',
                'nomeUsuario' => 'edu_rocha',
                'emailUsuario' => 'edu.rocha@gmail.com',
                'senhaUsuario' => Hash::make('123456'),
                'nacionalidadeUsuario' => 'Brasileiro',
                'dataNascimentoUsuario' => '1998-12-01',
                'fotoPerfilUsuario' => null,
                'fotoBannerUsuario' => null,
                'bioUsuario' => 'Maratonista apaixonado por desafios.',
                'alturaCm' => 180.0,
                'pesoKg' => 75.0,
                'peDominante' => 'direito',
                'maoDominante' => 'direita',
                'generoUsuario' => 'Masculino',
                'esporte' => 'Atletismo',
                'posicao' => 'Corredor',
                'estadoUsuario' => 'Pernambuco',
                'cidadeUsuario' => 'Recife',
                'categoria' => 'Profissional',
                'temporadasUsuario' => '8'
            ],
            [
                'nomeCompletoUsuario' => 'Larissa Gomes Pinto',
                'nomeUsuario' => 'lari_pinto',
                'emailUsuario' => 'lari.pinto@gmail.com',
                'senhaUsuario' => Hash::make('123456'),
                'nacionalidadeUsuario' => 'Brasileira',
                'dataNascimentoUsuario' => '2006-09-05',
                'fotoPerfilUsuario' => null,
                'fotoBannerUsuario' => null,
                'bioUsuario' => 'Jogadora de futsal escolar.',
                'alturaCm' => 165.0,
                'pesoKg' => 55.0,
                'peDominante' => 'direito',
                'maoDominante' => 'esquerda',
                'generoUsuario' => 'Feminino',
                'esporte' => 'Futsal',
                'posicao' => 'Meio-campo',
                'estadoUsuario' => 'Rio Grande do Sul',
                'cidadeUsuario' => 'Porto Alegre',
                'categoria' => 'Escolar',
                'temporadasUsuario' => '1'
            ],
            [
                'nomeCompletoUsuario' => 'Pedro Henrique Almeida',
                'nomeUsuario' => 'pedroha',
                'emailUsuario' => 'pedroha@gmail.com',
                'senhaUsuario' => Hash::make('123456'),
                'nacionalidadeUsuario' => 'Brasileiro',
                'dataNascimentoUsuario' => '2000-01-10',
                'fotoPerfilUsuario' => null,
                'fotoBannerUsuario' => null,
                'bioUsuario' => 'Jogador de tênis e amante de esportes ao ar livre.',
                'alturaCm' => 183.0,
                'pesoKg' => 77.0,
                'peDominante' => 'direito',
                'maoDominante' => 'direita',
                'generoUsuario' => 'Masculino',
                'esporte' => 'Tênis',
                'posicao' => 'Jogador',
                'estadoUsuario' => 'Ceará',
                'cidadeUsuario' => 'Fortaleza',
                'categoria' => 'Profissional',
                'temporadasUsuario' => '5'
            ],
            [
                'nomeCompletoUsuario' => 'Sofia Reis Martins',
                'nomeUsuario' => 'sofiamartins',
                'emailUsuario' => 'sofiamartins@gmail.com',
                'senhaUsuario' => Hash::make('123456'),
                'nacionalidadeUsuario' => 'Brasileira',
                'dataNascimentoUsuario' => '2007-10-15',
                'fotoPerfilUsuario' => null,
                'fotoBannerUsuario' => null,
                'bioUsuario' => 'Promessa do skate feminino nacional.',
                'alturaCm' => 160.0,
                'pesoKg' => 50.0,
                'peDominante' => 'esquerdo',
                'maoDominante' => 'esquerda',
                'generoUsuario' => 'Feminino',
                'esporte' => 'Skate',
                'posicao' => 'Skatista',
                'estadoUsuario' => 'Santa Catarina',
                'cidadeUsuario' => 'Florianópolis',
                'categoria' => 'Juvenil',
                'temporadasUsuario' => '2'
            ],
        ];

        DB::table('atletas')->insert($atletas);
    }
}
